"""
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *  find the sum of the even-valued terms.
"""


def get_sum_of_even_fibonacci_numbers_below(n: int) -> int:
    n1 = 1
    n2 = 2
    counter = 0
    while n2 < n:
        if n2 % 2 == 0:
            counter += n2
        temp = n2 + n1
        n1 = n2
        n2 = temp
    return counter


print(f'Sum of even numbers below 4kk is: {get_sum_of_even_fibonacci_numbers_below(4_000_000)}')
